# Generated by Django 5.1.3 on 2024-12-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0002_professional_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
